---
title: "geocode"
author: "Arielle Herman"
date: "2/12/2022"
output: html_document
---
```{r}
library(ggmap)
library(tidyverse)
readRDS("../data/processed/survey.rds")
```

```{r eval=F}
#jsonlite::fromJSON("https://data.cityofnewyork.us/resource/7t3b-ywvw.json")

nybb <- sf::st_read("../data/input/borough_boundaries/borough_boundary.shp")
sf_geocoded <- zipcodes_geocoded %>% filter(lon < 42) %>% select(responseid, lat, lon) %>% na.omit() %>% sf::st_as_sf(coords = c("lon", "lat"), crs = 4326)
zipcodes_geocoded$address
sf_inter <- intersections_geocoded[c("lon", "lat")] %>% na.omit() %>% sf::st_as_sf(coords = c("lon", "lat"), crs = 4326)
ggplot() + geom_sf(data = nybb) + geom_sf(data = sf_geocoded)
ggplot()  + #geom_sf(data = nybb) +
  geom_sf(data = )
  geom_sf(data = sf_geocoded)
  
  range(zipcodes_geocoded$lat, na.rm = TRUE)
  
xmin <- -74.25559
ymin <- 40.49613
xmax <- -73.70001
ymax <- 40.91553

filter(zipcodes_geocoded) %>% filter(lat < xmax)
zipcodes_geocoded$lat %>% range(na.rm = TRUE)

dist <- wrangled %>% count(borough) %>% mutate_at(vars(borough), ~str_to_title(str_replace(., "si", "staten island"))) %>% na.omit

dist

nybb %>% left_join(dist, by = c("boro_name" = "borough")) %>%
  ggplot() + geom_sf(aes(fill = n))

```


## geocode

```{r eval=F}

# doesn't always but the name of the borough

today <- gsub("-", "", Sys.Date())
borough_names <- c("manhattan", "new york", "bronx", "staten island", "brooklyn", "queens")
geocoded_file_path <- paste0("../data/processed/zipcodes_geocoded", today, ".csv")

if(file.exists(geocoded_file_path)) {
  zipcodes_geocoded <- read_csv(geocoded_file_path)
} else {
  zipcodes <- survey %>% filter(!is.na(q3))
  zipcodes_geocoded <- zipcodes %>%
    ggmap::mutate_geocode(q3, output = "more")# %>%
    #filter(borough_coded = str_extract())
    #select(responseid, q3, address, lon, lat)
  write_csv(zipcodes_geocoded, geocoded_file_path)
  intersections_geocoded <- survey %>% filter(!is.na(q4)) %>% ggmap::mutate_geocode(q4, output = "more")
}

geocoded <-lapply(list(zipcodes_geocoded, intersections_geocoded), function(df) {
  df %>% select(responseid, address, lon, lat)
}) %>% reduce(full_join, by = c("responseid")) %>% mutate(kept = responseid %in% wrangled$responseid)

saveRDS(geocoded, "../data/output/geocoded.rds")

# coding the intersections is less accurate
#intersections <- survey %>% filter(!is.na(q4))
#geocoded <- intersections %>% ggmap::mutate_geocode(q4, output = "more")

## however, there are three postal codes that the geocoding fails to recognize
zipcodes_geocoded %>%
  arrange(responseid) %>% select(responseid, address, q3, q4, type) %>%
  filter(responseid %in% c("r_1gafr4up5ko8gyd", "r_1qb2mivxdjbz2q1", "r_2tnhe7vqp6gyj3z"))

zipcodes_geocoded %>% select(responseid, lat, lon) %>%
  full_join(intersections)
## example
wrong <- ggmap::geocode(postalcode = "10368", output = "more")

## also doesn't work to paste intersection and geocode together
#geocode_full_address <- survey %>%
#  filter(!is.na(q3) | !is.na(q4)) %>%
#  mutate(full_address = paste(q4, q3, sep = ", ")) %>%  mutate_geocode(full_address, output = "more")
geocoded %>% arrange(responseid) %>% select(responseid, lat, lon) %>% filter(responseid == "r_03b2jtpcmbdrzup") %>% distinct
```

```{r}
map <- urbnmapr::get_urbn_map("states", sf = TRUE)
filter(state_abv == "NY")
```
