---
title: "Panel Data vs. Online Responses"
author: "Arielle Herman"
date: "6/16/2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source("../default_setup.R")
```

# Demographic Distribution in Panel Data vs. Online Responses

Below are basic bar plots that compare the demographic distributions of panel and online respondents in the following categories:

1. Gender
2. Race (census categories)
3. Marital Status
4. Religion
5. Sexual Orientation
6. Language Spoken at Home
7. Level of Education

```{r}
demographic_qs <- c("gen", "race_census", "mar", "relig", "sex", "not_eng", "sch_level")

plots <- lapply(demographic_qs, function(q) {
  sym_q <- sym(q)
  
  # hackey text fixes
  q_text <- survey_codebook_labelled$text[survey_codebook_labelled$full_name == q] %>%
    str_replace_all(c("(?<=completed).*" = "?", " \\(select one\\)" = ""))
  if(length(q_text) == 0) {
    q_text <- "Census Race Category"
  }
  
  plot <- wrangled %>%
    count(source = source == "eme", !!sym_q) %>%
    na.omit %>%
    mutate(across(!!sym_q,
                  ~stringi::stri_trans_general(stringr::str_to_title(labelled::to_factor(.)),
                                               "latin-ascii")),
           # hackey text fixes
           across(!!sym_q, ~str_replace_all(., c("Transgender.*" = "Transgender",
                                                 "Indigenous.*" = "Indigenous American",
                                                 "^Yes$" = "Not English at Home",
                                                 "^No$" = "English at Home")))) %>%
    ggplot() + geom_col(aes(x = n, y = reorder(!!sym_q, n), fill = source), position = "dodge") +
    scale_fill_manual(NULL, labels = c("Online Responses", "Panel (Emerson)"), values = project_pal[c(1,3)]) +
    ylab(NULL) + xlab(NULL) + ggtitle(str_to_sentence(q_text)) +
    theme(legend.position = "bottom")
  return(plot)
    #ggtitle(glue::glue("Income Distribution by {facet}"))
})
plots

```