---
title: "Status Update"
author: "Communities Speak Spring 2022 Survey"
date: "4/13/2022"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
source("default_setup.R")
setwd("~/communities_speak/sp22")
load("data/processed/final_clean.rdata")
```

# Responses Over Time

```{r echo=F}
final_clean %>%
  filter(valid == 1) %>%
  mutate(week = lubridate::week(recordeddate)-14) %>%
  group_by(source, week) %>% count %>% arrange(source, week) %>%
  group_by(source) %>%
  mutate(cum = cumsum(n), label = ifelse(cum == max(cum), as.character(cum), "")) %>%
  filter(max(cum) >= 10) %>%
  ggplot(aes(x = factor(week), y = cum, group = source, color = source)) +
  geom_point() + geom_line(show.legend = FALSE) +
  ggrepel::geom_text_repel(aes(label = label), show.legend = FALSE, seed = 1) +
  xlab("\nActive Weeks of Survey") + ylab("Cummulative Responses\n") +
  ggtitle("Cummulative Responses Over Time\n") +
  scale_color_discrete(glue::glue("N = {sum(final_clean$valid == 1, na.rm = TRUE)}")) +
  guides(color = guide_legend(title.position = "bottom", title.hjust = 0.3))
```

# Response Statistics

perhaps a week by week total or mean?

```{r echo=F, warning=F, message=F, results = "asis"}
lang <- tribble(~userlanguage, ~language,
                "en", "English",
                "fr", "French",
                "zh-s", "Simplified Chinese",
                "es-es", "Spanish",
                "ar", "Arabic")

total <- final_clean %>%
  summarize(source = "total",
            language = NA_character_,
            total = sum(!is.na(valid), na.rm = TRUE),
            `valid responses` = sum(valid, na.rm = TRUE),
            percent = round(mean(valid, na.rm = TRUE), 2))

update <- final_clean %>% #filter(valid == 1) %>% 
  group_by(source, userlanguage) %>%
  summarize(percent = round(mean(valid, na.rm = TRUE), 2),
            total = n(),
            `valid responses` = sum(valid, na.rm = TRUE)) %>%
  left_join(lang) %>% select(source, language, `valid responses`, total, percent) %>%
  bind_rows(total)

kableExtra::kable(update)
```

# Demographics

