---
title: "Underlying Distributions"
author: "Arielle Herman"
date: "5/25/2022"
output:
  pdf_document:
    toc: true
---
 

```{r setup, include=FALSE}
source("../../code/default_setup.R")
fin_sec_dem <- c("gen", "hh_sn_65_bi", "hh_ch_0_17_bi", "race_census", "borough")
```

# Weighting Variables

The below plot indicates the existence and relative number of respondents in each cross-tabulated category of the desired weighting variables:

1. race
2. gender
3. borough

```{r echo = F}
boroughs <- unique(wrangled$borough)

wrangled %>%
    mutate(gen_label = labelled::to_factor(gen),
           gen = as.factor(ifelse(gen >= 3, 3, gen)),
           across(c(race_census, gen_label),
                    ~str_to_title(str_replace_all(.,
                                                  c("transgender.*|non.*|pref.*" = "other",
                                                    "indigenous.*" = "Indigenous American",
                                                    "white.*" = "white",
                                                    "black.*" = "black",
                                                    "hisp.*" = "hispanic",
                                                    "native haw.*" = "pacific islander"))))) %>%
    count(race_census, gen, gen_label, borough) %>% na.omit %>%
    
    ggplot(aes(x = gen, y = race_census, color = gen_label)) + geom_point(aes(size = n)) +
    ggtitle("Distribution of Race and Gender by Borough") +
    ylab("Race (as per 2020 Census definition)\n") + xlab("Gender") + facet_grid(. ~ borough) +
    theme(axis.text.x.bottom = element_blank()) +
    scale_color_manual("Gender", values = project_pal[c(1,3,5)])
```

```{r, include = F}
dict <- tribble(~var, ~label,
        "ucgid", c("bronx" = 5,
                    "brooklyn" = 47,
                    "manhattan" = 61,
                    "queens" = 81,
                    "staten island" = 85),
        "ptdtrace", c("white" = 1,
                  "black" = 2,
                  "american indian, alaskan native" = 3,
                  "asian" = 4,
                  "hawaiian/pacific islander only" = 5,
                  "two or more" = 6,
                  "hispanic" = 7),
        "sex", c("male" = 1,
                 "female" = 2),
        "hfaminc", c("Less than $5,000" = 1,
                     "$5,000 to $7,499" = 2,
                     "$7,500 to $9,999" = 3,
                     "$10,000 to $12,499" = 4,
                     "$12,500 to $14,999" = 5,
                     "$15,000 to $19,999" = 6,
                     "$20,000 to $24,999" = 7,
                     "$25,000 to $29,999" = 8,
                     "$30,000 to $34,999" = 9,
                     "$35,000 to $39,999" = 10,
                     "$40,000 to $49,999" = 11,
                     "$50,000 to $59,999" = 12,
                     "$60,000 to $74,999" = 13,
                     "$75,000 to $99,999" = 14,
                     "$100,000 to $149,999" = 15,
                     "$150,000 and over" = 16),
        "inc", c("1" = list(1:4),
                 "2" = list(5:10), # inclusive of $36,500 but exceeding
                 "3" = list(11:13), # inclusive again
                 "4" = list(14:16)
                 )
        )
flatten(dict$label[dict$var == "inc"])$`1`

get_cps <- function(query) {
  result <- httr::GET(query)
  as_list <- jsonlite::fromJSON(rawToChar(result$content))
  column_names <- unlist(as_list[1])
  
  as_df <- lapply(as_list[2:length(as_list)], function(row) {
    names(row) <- column_names
    return(row)
  }) %>% bind_rows %>%
    pivot_longer(cols = matches("[1-9]"), names_to = "hfaminc", values_to = "tabulate") %>%
    mutate(ucgid = str_extract(ucgid, "[:digit:]{2}$"),
           across(everything(), as.numeric)) %>%
    rename_all(str_to_lower)
  
  df_labelled <- lapply(colnames(as_df), function(col) {
    if(col %in% dict$var) {
      label <- unlist(dict$label[dict$var == col])
      as_df[col] %>% mutate_at(col, ~haven::labelled(., label))
    } else {
      as_df[col]
    }
  }) %>% bind_cols
  
  
  
  return(df_labelled)
  
}

inc_labels <- attributes(wrangled$inc_before)$labels
out <- get_cps(query = "https://api.census.gov/data/2022/cps/basic/may?tabulate=weight(PWSSWGT)&col+HEFAMINC&row+PTDTRACE&row+ucgid&ucgid=0500000US36005,0500000US36047,0500000US36061,0500000US36081,0500000US36085") %>%
  mutate(inc_before = case_when(
  hfaminc <= 4 ~ 1,
  hfaminc <= 10 ~ 2,
  hfaminc <= 13 ~ 3,
  hfaminc <= 16 ~ 4
)) %>% mutate(inc_before = haven::labelled(inc_before, inc_labels)) %>%
  group_by(ucgid, inc_before) %>% summarize(tabulate = sum(tabulate)) %>%
  rename(borough = ucgid, n = tabulate) %>%
  group_by(borough) %>%
  mutate(prop = n/sum(n), source = "CPS")
  
```
# Two Plots to Visualize Income Distribution

```{r echo=F, warning=F, message=F}
categories <- attributes(wrangled$inc_after)$labels
arranged <- tibble(range = names(categories)) %>%
  left_join(wrangled %>% mutate(range = labelled::to_character(inc_before)) %>%
              count(range, inc_before)) %>%
  mutate(range = str_replace_all(range, c("under" = "$0 -", "or above" = "- $400,001+"))) %>%
  separate(col = range, into = c("min", "max"), sep = " - ", remove = FALSE) %>%
  mutate(across(min:max, ~as.double(str_replace_all(., "\\$|,|\\+", "")))) %>%
  
  na.omit()# come back to top bracket later
arranged %>%
  mutate(inc_before = labelled::to_factor(inc_before)) %>%
  ungroup() %>%
  ggplot(aes(fill = inc_before)) +
  
  geom_rect(aes(xmin = min, xmax = max, ymin = 0, ymax = n), color = background) +
  geom_label(aes(x = (min + max)/2, y = n + 20, label = n, color = inc_before),
             fill = background, show.legend = FALSE) +
  
  scale_fill_manual(NULL, values = project_pal) +
  scale_color_manual(NULL, values = project_pal) +
  scale_x_continuous(labels = scales::dollar) +
  
  xlab(NULL) + ylab(NULL) +
  ggtitle("Respondent Income Distribution 2021") +
  theme(legend.position = "bottom")

inc_dist_plot <- arranged %>%
  
  ggplot(aes(y = reorder(range, max)), color = project_pal[1], show.legend = FALSE) +
  #geom_col(aes(x = max)) +
  geom_linerange(aes(xmin = min, xmax = max, size = n,  alpha = n),
                 color = project_pal[1], show.legend = FALSE) +
  geom_vline(xintercept = c(35000, 69500),
             #labels = c("poverty line", "median income"),
             lty = "dashed") +
  geom_text(aes(x = max, label = n), hjust = -0.2, color = project_pal[1], size = 3, show.legend = FALSE) +
  scale_x_continuous(labels = scales::dollar) +
  #annotate("text", x = 0, y = c(poverty_line), label = c("Respondents\nBelow Poverty Line"))
  #geom_jitter(data = wrangled, aes(x = ))
  ylab("Income Bracket\n") + xlab("\nIncome Range") +
  ggtitle("Respondent Income Distribution\n")
inc_dist_plot
```

# Income Distribution by Demographic (to be completed)

```{r echo=F, warning=F, message=F}
lapply(fin_sec_dem, function(facet) {
  sym_facet <- sym(facet)
  
  counted <- wrangled %>% select(inc_before, !!sym_facet) %>%
    mutate(across(!!sym_facet, labelled::to_factor),
           across(!!sym_facet,
                    ~str_replace_all(., c("transgender.*|non.*|pref.*" = "other",
                                         "indigenous.*" = "ind. amrcn",
                                         "white.*" = "white",
                                         "black.*" = "black",
                                         "hisp.*" = "hispanic",
                                         "native haw.*" = "pac. islndr",
                                         "two.*" = "two plus")))) %>%
    count(!!sym_facet, inc_before) %>% na.omit %>%
    group_by(!!sym_facet) %>%
    mutate(prop = n/sum(n)) %>%
    mutate(source = "CS")
  
  if(facet == "borough") {
    counted <- counted %>% bind_rows(out %>% mutate(borough = to_factor(borough)))
  }
  
  plotted <- counted %>%
    ggplot() + geom_col(aes(x = inc_before, y = prop, fill = source), position = "dodge") +
    facet_grid(cols = vars(!!sym_facet)) +
    ggtitle(glue::glue("Income Distribution by {facet}")) +
      scale_y_continuous(labels = scales::percent) +
    scale_fill_manual(NULL, values = project_pal[c(1,3)])
  
  if(length(unique(counted$source)) == 1) {
    plotted <- plotted + theme(legend.position = "none")
  }
  
  return(plotted)

})

```

# Employment (to do)

# Households (to be completed)

```{r echo=F, warning=F, message=F}
wrangled %>%
  select(inc_before, fin_sec_dem) %>%
  mutate(across(c(hh_ch_0_17_bi, hh_sn_65_bi),
                ~str_replace_all(labelled::to_factor(.),
                                 c("household" = "hh"#,
                                   #"children" = "kids",
                                   #"seniors" = "srs"
                                   )))) %>%
  ggplot() + geom_bar(aes(x = inc_before)) + 
  facet_grid(vars(hh_sn_65_bi), vars(hh_ch_0_17_bi))
```